---
- name: Update package
  command: apt update
  notify: 
    - Install Java
    - Create Tomcat group
    - Create Tomcat user
    - Create Tomcat directory & change ownership to directory
    - Download Tomcat
    - Extract Tomcat
    - Update permissions
    - Create systemd service file for Tomcat
    - Reload systemd daemon
    - Configure tomcat-users.xml
    - Configure context.xml
    - Ensure tomcat-users.xml permissions
    - Enable and start Tomcat
    
