- name: Apply configurations based on group_vars
  hosts: "{{ HOSTS }}"
  vars:
    HOSTS_VARS: "{{ HOSTS_FILE | default('adq_ubuntudesktop.yaml') }}"
    SOFTWARE_FILE: "{{ SOFTWARE_FILES | default('all.yaml') }}"
  vars_files:
    - "./environments/dev/groups/{{ HOSTS_VARS }}"

  tasks:
    - name: Include software variables if specified
      include_vars:
        file: "./softwares/{{ item }}"
      loop: "{{ SOFTWARE_FILES.split(',') }}"
      loop_control:
        loop_var: item
      when: SOFTWARE_FILE != 'all.yaml'

    - name: Apply roles in a loop
      include_role:
        name: "{{ item.role_name }}"
      loop: "{{ roles_to_apply }}"
