---
- name: Apply configurations based on group_vars
  hosts: "{{ HOSTS }}"
  vars:
    HOSTS_VARS: "{{ HOSTS_FILE | default('adq_ubuntudesktop.yaml') }}"
  vars_files:
    - "./environments/{{ env }}/groups/{{ HOSTS_VARS }}"
  
  tasks:
    - include_role:
        name: "{{ item }}"
      loop:
        - java
        - python
        - tomcat
        - ubuntudesktop
        - notepad++
      when: tags is not defined or tags | intersect(['all_softwares', 'java', 'python', 'tomcat', 'ubuntudesktop', 'notepad++']) | length > 0
