---
- name: Apply configurations based on group_vars
  hosts: all
  
  tasks:
    - name: Include roles if tags match
      include_role:
        name: "{{ item }}"
      loop:
        - java
        - python
        - tomcat
        - ubuntudesktop
        - notepad++
