---
- name: Apply configurations based on group_vars
  hosts: "{{ HOSTS }}"
  vars:
    HOSTS_VARS: "{{ HOSTS_FILE | default('adq_ubuntudesktop.yaml') }}"
  vars_files:
    - "./environments/{{ env }}/groups/{{ HOSTS_VARS }}"
  
  tasks:
    - name: Include roles if tags match
      include_role:
        name: "{{ item }}"
      loop:
        - java
        - python
        - tomcat
        - ubuntudesktop
        - notepad++
      when: tags == 'all_softwares' 

