- name: Apply configurations based on group_vars
  hosts: "{{ HOSTS }}"
  vars:
    HOSTS_VARS: "{{ HOSTS_FILE | default('adq_ubuntudesktop.yaml') }}"
    SOFTWARE_FILES: "{{ SOFTWARE_FILES | default('all.yaml') }}"
  vars_files:
    - "./environments/dev/groups/{{ HOSTS_VARS }}"

  tasks:
    - name: Apply roles and include software variables if specified
      include_vars:
        file: "./softwares/{{ item }}"
      loop: "{{ SOFTWARE_FILES.split(',') }}"
      when: SOFTWARE_FILES != 'all.yaml'
      include_role:
        name: "{{ item.role_name }}"
      loop: "{{ roles_to_apply }}"
