---
- import_playbook: playbook_softwares.yml
  when: action == "apply"
- import_playbook: playbook_services.yml
  when: action == "apply"
- import_playbook: playbook_deployment.yml
  when: action == "apply"
- import_playbook: playbook_destroy.yml
  when: action == "destroy"
