---
- name: Apply configurations based on group_vars
  hosts: all
  
  roles:
    - name: Apply tags to tasks within included file
      include_role:
        name: java
        apply:
          tags:
            - java
      tags:
        - java
  
  #tasks
  #  - name: Include roles if tags match
  ##    include_role:
   #     name: "{{ item }}"
   #   loop:
   #     - java
    #    - python
     #   - tomcat
      #  - ubuntudesktop
       # - notepad++
