---
- name: Update package
  command: apt update
  become: yes

- name: Install Java{{ java_version | default('11') }}
  apt:
    name: openjdk-{{ java_version | default('11') }}-jdk
    state: present
  become: yes


