---
- name: Update package
  command: apt update
  when: ansible_action == "apply"

- name: Install Python3
  apt:
    name: python3
    state: present
  when: ansible_action == "apply"

- name: Install pip for Python3
  apt:
    name: python3-pip
    state: present
  when: ansible_action == "apply"
    
- name: Uninstall pip for Python3
  apt:
    name: python3-pip
    state: absent
  when: ansible_action == "destroy"

- name: Uninstall Python3
  apt:
    name: python3
    state: absent
  when: ansible_action == "destroy"
