---
- name: Uninstall Java, Python, Notepad++, Tomcat, and Ubuntu Desktop
  hosts: all
  become: yes
  roles:
    - name: Apply Java for destroy
      role: java-d
      tags: java-d
      
    - name: Apply tomcat for destroy
      role: tomcat-d
      tags: tomcat-d
      
    - name: Apply notepad++ for destroy
      role: notepad-d
      tags: notepad-d
      
    - name: Apply python for destroy
      role: python-d
      tags: python-d
      
    - name: Apply ubuntudesktop for destroy
      role: ubuntudesktop-d
      tags: ubuntudesktop-d
      
