---
- name: Update package
  command: apt update
  when: operation == "apply"

- name: Install Python{{ python_version }}
  apt:
    name: python{{ python_version }}
    state: present
  when: operation == "apply"

- name: Install pip for Python{{ python_version }}
  apt:
    name: python{{ python_version }}-pip
    state: present
  when: operation == "apply"
    
- name: Uninstall pip for Python{{ python_version }}
  apt:
    name: python{{ python_version }}-pip
    state: absent
  when: operation == "destroy"

- name: Uninstall Python{{ python_version }}
  apt:
    name: python{{ python_version }}
    state: absent
  when: operation == "destroy"
